### ISSUE TITLE
This project is not having web.xml file

### ISSUE THREAD

**Issue by khushwinder** [sivaprasadreddy/maven-archetype-templates#1]
This project is not having web.xml file. Please add it.

thanks

**Comment by sivaprasadreddy** [comment]
The root maven project is of om type. Which archetype you are referring to?

**Comment by khushwinder** [comment]
i downloaded all your project using the following url
https://github.com/sivaprasadreddy/maven-archetype-templates.git
but after that when i tried to import one of those ie. quickstart-springmvc-angularjs project in eclipse as maven project i got the maven issue ie This project is not having web.xml file. Then after that i had to add tag in pom.xml as false <findNoWeb....

**Comment by sivaprasadreddy** [comment]
Fixed by adding &lt;failOnMissingWebXml&gt; in &lt;properties&gt;.
